language: php
php:
  - "7.2"

# sudo: required
# dist: trusty

# addons:
#   chrome: stable

env:
  global:
    - setup=basic
    - APP_ENV=staging
    - APP_DEBUG=true
    - DB_CONNECTION=sqlite
    - CACHE_DRIVER=file
    - SESSION_DRIVER=file
    - QUEUE_DRIVER=sync

install:
  - make install
  # - npm i
  # - cp .env.testing .env
  # - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - touch database/database.sqlite
  - php artisan migrate
  # - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  # - make s &

script:
  - make test
  # - npm run travis
  # - php artisan dusk

after_script:
  - vendor/bin/test-reporter