language: php
php:
  - "7.1"

install:
  - composer self-update
  - make install

before_script:
  - touch database/database.sqlite
  - php artisan migrate

script: make test

after_script:
  - vendor/bin/test-reporter