language: php
php:
  - "7.2"

# sudo: required
# dist: trusty

# addons:
#   chrome: stable

install:
  - make install
  # - npm i
  # - cp .env.testing .env
  # - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - touch database/database.sqlite
  - php artisan migrate
  # - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  # - make s &

script:
  - npm run travis
  # - php artisan dusk

after_script:
  - vendor/bin/test-reporter